/**
 * The Perf HUD's readout — a passive observability overlay. The component is
 * in canvas-huds.tsx; values sit in fixed-width slots so they can update each
 * frame without shifting horizontally.
 *
 * No load is generated by enabling this — it just reads metrics computed
 * elsewhere (the frame loop's rolling frame-time window, live counts from
 * tone-synth.ts, planchette count from store, live-voice mode from
 * live-voice.ts).
 */
export interface PerfHudMetrics {
  frameMsP50: number;
  frameMsP99: number;
  synthCount: number;
  oscillatorCount: number;
  voiceCount: number;
  audioBaseLatencyMs: number;
  /** Where live voices are smoothed (BACKLOG 15.7). */
  liveVoiceMode: string;
}

/** What the Perf HUD shows, as text. */
export interface PerfReadout {
  frame: string;
  synths: string;
  oscs: string;
  voices: string;
  audio: string;
}

export function perfReadout(m: PerfHudMetrics): PerfReadout {
  return {
    frame: `${m.frameMsP50.toFixed(1)} / ${m.frameMsP99.toFixed(1)} ms`,
    synths: String(m.synthCount),
    oscs: String(m.oscillatorCount),
    voices: String(m.voiceCount),
    audio: `${m.audioBaseLatencyMs.toFixed(1)} ms latency · live: ${m.liveVoiceMode}`,
  };
}
