/**
 * Perf HUD — passive observability overlay. Mirrors the Pitch HUD pattern:
 * caller owns the host element; this module fills it in and toggles
 * visibility. The host is a single absolute-positioned <div>; we render three
 * spans of fixed-width slots so values can update each frame without
 * shifting horizontally.
 *
 * No load is generated by enabling this — it just reads metrics computed
 * elsewhere (rolling frame-time buffer in main.ts, live counts from
 * tone-synth.ts, planchette count from store).
 */
export interface PerfHudMetrics {
  frameMsP50: number;
  frameMsP99: number;
  synthCount: number;
  oscillatorCount: number;
  voiceCount: number;
  audioBaseLatencyMs: number;
}

export interface PerfHud {
  setVisible(visible: boolean): void;
  refresh(m: PerfHudMetrics): void;
}

export function createPerfHud(host: HTMLElement): PerfHud {
  host.innerHTML = `
    <div class="perf-hud-row">
      <span class="perf-hud-label">Frame</span>
      <span class="perf-hud-val" id="perf-frame">—</span>
    </div>
    <div class="perf-hud-row">
      <span class="perf-hud-label">Synths</span>
      <span class="perf-hud-val" id="perf-synths">—</span>
      <span class="perf-hud-label">Oscs</span>
      <span class="perf-hud-val" id="perf-oscs">—</span>
      <span class="perf-hud-label">Voices</span>
      <span class="perf-hud-val" id="perf-voices">—</span>
    </div>
    <div class="perf-hud-row">
      <span class="perf-hud-label">Audio</span>
      <span class="perf-hud-val" id="perf-audio">—</span>
    </div>
  `;

  const frameEl = host.querySelector('#perf-frame') as HTMLSpanElement;
  const synthsEl = host.querySelector('#perf-synths') as HTMLSpanElement;
  const oscsEl = host.querySelector('#perf-oscs') as HTMLSpanElement;
  const voicesEl = host.querySelector('#perf-voices') as HTMLSpanElement;
  const audioEl = host.querySelector('#perf-audio') as HTMLSpanElement;

  let lastFrame = '';
  let lastSynths = -1;
  let lastOscs = -1;
  let lastVoices = -1;
  let lastAudio = '';

  return {
    setVisible(visible) {
      if (visible) {
        if (host.hasAttribute('hidden')) host.removeAttribute('hidden');
      } else {
        if (!host.hasAttribute('hidden')) host.setAttribute('hidden', '');
      }
    },
    refresh(m) {
      const frame = `${m.frameMsP50.toFixed(1)} / ${m.frameMsP99.toFixed(1)} ms`;
      if (frame !== lastFrame) { frameEl.textContent = frame; lastFrame = frame; }
      if (m.synthCount !== lastSynths) { synthsEl.textContent = String(m.synthCount); lastSynths = m.synthCount; }
      if (m.oscillatorCount !== lastOscs) { oscsEl.textContent = String(m.oscillatorCount); lastOscs = m.oscillatorCount; }
      if (m.voiceCount !== lastVoices) { voicesEl.textContent = String(m.voiceCount); lastVoices = m.voiceCount; }
      const audio = `${m.audioBaseLatencyMs.toFixed(1)} ms latency`;
      if (audio !== lastAudio) { audioEl.textContent = audio; lastAudio = audio; }
    },
  };
}
